name: BoxMigrator
main: net.okocraft.box.migrator.BoxMigrator
version: ${project.version}
author: Siroshun09
api-version: 1.17
depend: ["Box"]
commands:
  boxmigrate:
    description: "Migrate data from v3 database"
