storage:
  type: "yaml" # or sqlite
  database:
    table_prefix: "box_"
  sqlite:
    filename: "box-sqlite.db"
  yaml:
    directory-name: "data"

stock-data-save-interval: 180 # seconds

disabled-worlds:
  - example_world_name
disabled-features:
  - example_feature_name

stick:
  menu-command: "box gui"

debug: false
