storage:
  type: "yaml" # yaml, sqlite, or mysql
  yaml:
    directory-name: "data"
  sqlite:
    table-prefix: "box_"
    filename: "box-sqlite.db"
  mysql:
    table-prefix: "box_"
    address: "localhost"
    port: 3306
    database-name: "box"
    username: ""
    password: ""

stock-data-save-interval: 180 # seconds

disabled-worlds:
  - example_world_name
disabled-features:
  - example_feature_name

stick:
  menu-command: "box gui"

debug: false
