debug: false
item:
  enable-defaults: true
  enable-potions: false
  enable-enchanted-books: false
  enable-firework-rockets: false
disabled-worlds:
  - example_world_name
disabled-features:
  - example_feature_name
stick:
  menu-command: "box gui"
