name: Box
version: '${projectVersion}'
description: A Paper plugin that has infinite (2.1 billion) containers for each item.
main: net.okocraft.box.plugin.BoxPlugin
bootstrapper: net.okocraft.box.bootstrap.BoxBootstrap
api-version: '1.17'

dependencies:
  server:
    CoreProtect:
      required: false
    LWC:
      required: false
    Bolt:
      required: false
