name: Gradle Build
on: [ push, pull_request ]

jobs:
  build-java-17:
    uses: okocraft/workflows/.github/workflows/gradle.yml@v1
    with:
      java-version: '17'
      build-arguments: "build"
      package-name: Box-Build-${{ github.run_number }}
      artifact-directory: "./build/libs"
  build-java-21:
    uses: okocraft/workflows/.github/workflows/gradle.yml@v1
    with:
      java-version: '21'
      build-arguments: "build"
      package-name: Box-Build-${{ github.run_number }}
      artifact-directory: "./build/libs"
