name: Maven Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 16
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'temurin'
          java-version: '16'
          cache: 'maven'
      - name: Build with Maven
        run: |
          mvn clean
          mvn -B package --file pom.xml
      - name: Move the artifact
        run: |
          mkdir staging
          cp -r target/ staging
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging
